[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.24"
remappings = ["@openzeppelin/=lib/openzeppelin-contracts/"]

[rpc_endpoints]
# Avalanche (default)
avalanche = "https://api.avax.network/ext/bc/C/rpc"
fuji = "https://api.avax-test.network/ext/bc/C/rpc"
# Extensible: add more EVM chains
# polygon = "https://polygon-rpc.com"
# base = "https://mainnet.base.org"
# ethereum = "https://eth.llamarpc.com"
